import type { Metadata } from "next";
export const metadata: Metadata = { title: "Terms of Service | DraftPilot", description: "Terms for using DraftPilot’s customer-support drafting service." };
export default function TermsPage() {
  return <article>
    <p className="legal-date">Last updated: 27 September 2026</p><h1>Terms of service</h1>
    <p className="legal-intro">These terms cover the DraftPilot website, workspace and browser extension, operated by DraftPilot in Bangladesh. Read them together with our <a href="/privacy">privacy policy</a> before using the service.</p>
    <h2>Your account and authority</h2><p>You must be an adult able to enter an agreement and have authority to act for any business whose workspace you manage. Keep account access secure and notify us if you suspect misuse. Workspace owners are responsible for granting appropriate team access.</p>
    <h2>Drafting assistance and human review</h2><p>DraftPilot helps generate replies from captured conversations, workspace knowledge and tone preferences. AI output can be incorrect, incomplete or inappropriate. You must review factual claims, customer commitments and sensitive information before inserting or sending any reply. You remain responsible for the messages you send. DraftPilot does not press your platform’s Send button.</p>
    <h2>Your content and permitted use</h2><p>You retain your rights to content you provide. You authorize DraftPilot and its service providers to process that content to operate the features you request. Only capture conversations and upload knowledge you are authorized to use, and provide any notices or permissions required by your customers, employer and applicable law.</p><p>Do not use DraftPilot for unlawful activity, unauthorized surveillance, credential theft, harassment, malware, or attempts to bypass access controls, quotas or payment requirements. Do not submit unnecessary passwords, payment-card details or specially regulated information without appropriate arrangements.</p>
    <h2>Plans and payment</h2><p>Available features, quotas, prices and billing intervals are shown in the product and checkout. A paid subscription starts only after you authorize checkout. Review the stated renewal and cancellation terms before purchasing. Contact <a href="mailto:support@draftpilot.com">support@draftpilot.com</a> for billing, cancellation or refund requests. Applicable statutory rights are not excluded by these terms.</p>
    <h2>Third-party platforms and availability</h2><p>Google, email and support platforms, AI providers and payment services have their own terms. DraftPilot is not endorsed by those platforms. Browser interfaces can change or restrict capture and insertion. Features depend on service availability, configured integrations and supported editors; uninterrupted operation and compatibility with every website are not guaranteed.</p>
    <h2>Suspension and account closure</h2><p>We may restrict access to address abuse, security incidents, nonpayment or legal requirements. You may stop using the service and request account closure through support. Workspace-owned records and retention obligations are handled as described in the privacy policy. Removing the extension alone does not cancel a subscription or delete an account.</p>
    <h2>Changes and questions</h2><p>We may update the service and these terms. The date above identifies this version; material changes will be communicated through the service or appropriate account channels. These terms do not remove rights that applicable law does not allow to be waived. For questions, contact DraftPilot, Bangladesh, at <a href="mailto:support@draftpilot.com">support@draftpilot.com</a>.</p>
  </article>;
}
