import type { Metadata } from "next";
export const metadata: Metadata = { title: "Privacy Policy | DraftPilot", description: "How DraftPilot handles account information, support conversations and AI drafting data." };
export default function PrivacyPage() {
  return <article>
    <p className="legal-date">Last updated: 27 September 2026</p><h1>Privacy policy</h1>
    <p className="legal-intro">DraftPilot is operated by DraftPilot, based in Bangladesh. This notice explains how information is handled when you use our website, workspace and browser extension.</p>
    <h2>Information we process</h2>
    <ul><li>Account details, such as your email, name, authentication identity and workspace membership.</li><li>Knowledge-base content, macros, tone preferences and workspace settings you provide.</li><li>Customer conversation text you capture or enable the extension to watch, and generated replies you request.</li><li>Usage and operational records, including draft counts, AI token use, subscription status, security events and service errors.</li></ul>
    <h2>Google sign-in</h2><p>Google sign-in supplies your basic account profile and email to authenticate you through Supabase. We request only email, profile and OpenID identity scopes. Signing in with Google does not grant Gmail mailbox access. The extension reads supported pages separately when you enable its capture or watch features.</p>
    <h2>Conversations and AI processing</h2><p>Captured text and relevant workspace knowledge are processed to prepare replies in your selected tone. Automated redaction attempts to remove common sensitive details, but can miss information. Review what you capture and avoid submitting passwords, payment-card information or other unnecessary sensitive data.</p><p>The selected AI service receives the context needed to generate a draft. Supported services include OpenAI and OpenRouter; OpenRouter may route requests to its selected model provider. Their processing locations and retention depend on the service and configuration. Contact us before submitting information subject to special handling requirements. Google sign-in credentials are not sent to the drafting model.</p><p>DraftPilot does not use customer conversations to train its own general-purpose AI model or sell Google account information. AI replies require human review and are never automatically sent by DraftPilot.</p>
    <h2>Why we use information</h2><p>We use information to authenticate accounts, operate workspaces, retrieve relevant knowledge, generate requested replies, enforce quotas, manage subscriptions, provide support and protect the service against misuse. Workspace administrators can manage access and view shared workspace content and usage.</p>
    <h2>Service providers and international processing</h2><p>We use Vercel for hosting and Supabase for authentication and database services. Our current production database is hosted in Singapore. Hosting and AI processing may occur outside Bangladesh or your country. When paid billing is enabled, Stripe handles payment processing; DraftPilot receives subscription records rather than full payment-card details. We may disclose information where legally required or necessary to investigate abuse and protect the service.</p>
    <h2>Storage and retention</h2><p>Knowledge sources and workspace records are stored to provide the service. Raw captured customer threads are not intentionally saved as draft-history records; generated replies and usage records are stored. Workspace draft-content retention settings offer 7, 30 or 90 days. Deletion requires the scheduled cleanup process; settings do not instantly erase records. Security, billing, backup and service-provider records can follow separate retention periods. Contact support for the current retention arrangements before relying on a deletion deadline.</p>
    <h2>Cookies and security</h2><p>We use authentication cookies and browser storage needed for sessions, preferences and extension pairing. Server credentials are kept out of the website and extension bundles. Access controls, encryption and other safeguards reduce risk, but no system can guarantee complete security.</p>
    <h2>Your choices and requests</h2><p>You can stop watching a conversation, remove the extension or revoke Google access in your Google Account settings. Revoking Google access does not delete your DraftPilot account or workspace records. Contact <a href="mailto:support@draftpilot.com">support@draftpilot.com</a> to request access, correction, export or deletion. We may verify your identity and coordinate with your workspace owner; shared business records and legally required records may need different handling. Rights available to you depend on applicable law.</p>
    <h2>Children, changes and contact</h2><p>DraftPilot is intended for adults using customer-support tools, not for children. We update this notice when our practices change and show the latest date above. For privacy questions or security reports, contact DraftPilot, Bangladesh, at <a href="mailto:support@draftpilot.com">support@draftpilot.com</a>.</p>
  </article>;
}
